import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import Database from "better-sqlite3";
import { afterEach, describe, expect, it } from "vitest";
import { openSeasonStore } from "../../src/infrastructure/sqlite/season-store.js";
import { LifecycleState, type CommandMetadata } from "../../src/application/ports/season-repository.js";

const actor = { type: "LOCAL_COMMISSIONER", label: "Commissioner" };
const rules = { limits: { QB: 2, RB: 2, WR: 3, TE: 2, K: 2, DST: 2 }, flexEligible: ["RB", "WR", "TE"], flexCapacity: 1 };
const dirs: string[] = [];
afterEach(async () => { await Promise.all(dirs.splice(0).map(path => rm(path, { recursive: true, force: true }))); });
const command = (seasonId: string, commandType: string, idempotencyKey = commandType): CommandMetadata => ({ actor, seasonId, commandType, idempotencyKey });

async function seeded(teamBalances: number[], playersPerTeam = 14) {
  const dir = await mkdtemp(join(tmpdir(), "u5-draft-")); dirs.push(dir); const path = join(dir, "db.sqlite"); const seasonId = `s-${Date.now()}-${Math.random()}`;
  let store = await openSeasonStore(path); await store.execute(command(seasonId, "CREATE"), tx => tx.createSeason({ id: seasonId, leagueId: `l-${seasonId}`, year: 2026, name: "U5", teamCount: teamBalances.length }));
  await store.configureTeams(command(seasonId, "TEAMS"), teamBalances.map((_, i) => ({ id: `team-${i}`, displayName: String.fromCharCode(65 + i), seedOrder: i + 1 })));
  const summary = await store.setupSummary(actor, seasonId); const positions = ["QB", "QB", "RB", "RB", "RB", "WR", "WR", "WR", "TE", "TE", "K", "K", "DST", "DST"] as const;
  for (let i = 0; i < teamBalances.length * playersPerTeam; i++) await store.addCustomPlayer(command(seasonId, `PLAYER-${i}`), { id: `p-${i}`, name: `Player ${i}`, position: positions[i % positions.length]!, sourceType: "LEAGUE_CUSTOM" });
  await store.close(); const db = new Database(path); db.prepare("UPDATE Season SET state='R2_PUBLISHED' WHERE id=?").run(seasonId); for (const [i, balance] of teamBalances.entries()) db.prepare("INSERT INTO TeamAuctionBalance(id,seasonId,seasonTeamId,roundNumber,startingBudget,spent,remainingBudget) VALUES(?,?,?,?,?,?,?)").run(`b-${i}`, seasonId, summary.teams[i]!.seasonTeamId, 2, balance, 0, balance); db.close(); store = await openSeasonStore(path); return { store, seasonId, teams: summary.teams, positions };
}

describe("permanent draft order", () => {
  it("ranks unique committed balances descending and freezes the order", async () => { const { store, seasonId, teams } = await seeded([100, 120, 80]); const result = await store.calculate(command(seasonId, "CALC")); expect(result.status).toBe("FINAL"); expect(result.order.map(item => item.seasonTeamId)).toEqual([teams[1]!.seasonTeamId, teams[0]!.seasonTeamId, teams[2]!.seasonTeamId]); await store.close(); });
  it("requires valid external precedence for every independent two/multi-team tie", async () => { const { store, seasonId } = await seeded([100, 100, 90, 90, 90]); const paused = await store.calculate(command(seasonId, "CALC")); expect(paused.ties.map(item => item.seasonTeamIds.length).sort()).toEqual([2, 3]); await expect(store.finalize(command(seasonId, "EARLY"))).rejects.toThrow("Missing external precedence"); const first = paused.ties.find(t => t.balance === 100)!; await expect(store.recordDraftOrderTieDecision(command(seasonId, "BAD"), { balance: 100, participantTeamIds: first.seasonTeamIds, precedenceTeamIds: [first.seasonTeamIds[0]!, first.seasonTeamIds[0]!], method: "draw", decidedAt: new Date().toISOString() })).rejects.toThrow("exactly once"); for (const tie of paused.ties) await store.recordDraftOrderTieDecision(command(seasonId, `TIE-${tie.balance}`), { balance: tie.balance, participantTeamIds: tie.seasonTeamIds, precedenceTeamIds: [...tie.seasonTeamIds].reverse(), method: "external draw", decidedAt: new Date().toISOString() }); const final = await store.finalize(command(seasonId, "FINAL")); const expected = [...paused.ties.find(t => t.balance === 100)!.seasonTeamIds].reverse().concat([...paused.ties.find(t => t.balance === 90)!.seasonTeamIds].reverse()); expect(final.order.map(item => item.seasonTeamId)).toEqual(expected); await store.close(); });
});

describe("fixed-order conventional drafting", () => {
  it("uses the unchanged Phase 1 limits and one shared FLEX for partial rosters", async () => { const { store, seasonId } = await seeded([120], 28); const order = await store.calculate(command(seasonId, "CALC")); const team = order.order[0]!.seasonTeamId; for (const id of ["p-0", "p-1"]) await store.makePick(command(seasonId, `P-${id}`), { seasonTeamId: team, playerId: id, rosterRules: rules }); await expect(store.makePick(command(seasonId, "QB-OVER"), { seasonTeamId: team, playerId: "p-14", rosterRules: rules })).rejects.toThrow("ROSTER_CAPACITY_EXCEEDED"); for (const id of ["p-2", "p-3", "p-4"]) await store.makePick(command(seasonId, `P-${id}`), { seasonTeamId: team, playerId: id, rosterRules: rules }); await expect(store.makePick(command(seasonId, "FLEX-OVER"), { seasonTeamId: team, playerId: "p-16", rosterRules: rules })).rejects.toThrow("ROSTER_CAPACITY_EXCEEDED"); await store.close(); });
  it("uses A-B-C-A order, rejects wrong/unavailable/overflow picks, and retries idempotently", async () => { const { store, seasonId, teams } = await seeded([120, 110, 100]); const order = await store.calculate(command(seasonId, "CALC")); const a = order.order[0]!.seasonTeamId, b = order.order[1]!.seasonTeamId, c = order.order[2]!.seasonTeamId; await expect(store.makePick(command(seasonId, "WRONG"), { seasonTeamId: b, playerId: "p-0", rosterRules: rules })).rejects.toThrow("on the clock"); let result = await store.makePick(command(seasonId, "P1", "same-pick"), { seasonTeamId: a, playerId: "p-0", rosterRules: rules }); const retry = await store.makePick(command(seasonId, "P1", "same-pick"), { seasonTeamId: a, playerId: "p-0", rosterRules: rules }); expect(retry.nextOverallPick).toBe(result.nextOverallPick); await expect(store.makePick(command(seasonId, "UNAVAILABLE"), { seasonTeamId: b, playerId: "p-0", rosterRules: rules })).rejects.toThrow("unavailable"); result = await store.makePick(command(seasonId, "P2"), { seasonTeamId: b, playerId: "p-1", rosterRules: rules }); result = await store.makePick(command(seasonId, "P3"), { seasonTeamId: c, playerId: "p-2", rosterRules: rules }); expect(result.currentSeasonTeamId).toBe(a); expect(result.nextOverallPick).toBe(4); await store.close(); });
  it("completes only with exactly 14 legal players per team and never snakes", async () => { const { store, seasonId } = await seeded([120, 110]); const order = await store.calculate(command(seasonId, "CALC")); const ids = order.order.map(item => item.seasonTeamId); for (let round = 0; round < 14; round++) for (let position = 0; position < 2; position++) { const overall = round * 2 + position; const result = await store.makePick(command(seasonId, `PICK-${overall}`), { seasonTeamId: ids[position]!, playerId: `p-${position * 14 + round}`, rosterRules: rules }); if (overall < 27) expect(result.currentSeasonTeamId).toBe(ids[(position + 1) % 2]); else expect(result.status).toBe("COMPLETED"); } expect((await store.getSeason(actor, seasonId))!.state).toBe(LifecycleState.COMPLETED); await store.close(); });
});
