import React, { useEffect, useRef, useState } from "react";

const emptyFilters={stage:"",commandType:"",entityType:"",correlationId:"",recordState:"",correctionLineage:""};

export function OperationsPanel({ seasonId, seasonVersion, onChanged }) {
  const [receipt, setReceipt] = useState(null); const [recovery, setRecovery] = useState(null); const [operations, setOperations] = useState(null); const [error, setError] = useState("");
  const [filters,setFilters]=useState(emptyFilters); const [loading,setLoading]=useState(false); const [pending,setPending]=useState(""); const loadSequence=useRef(0);
  const [targetKey,setTargetKey]=useState(""); const [reason,setReason]=useState(""); const [confirmation,setConfirmation]=useState(""); const [preview,setPreview]=useState(null);
  const request=async(path,options={})=>{const version=typeof seasonVersion==="function"?seasonVersion():seasonVersion;const response=await fetch(path,{...options,headers:{...(options.headers??{}),"idempotency-key":crypto.randomUUID(),...(version!==undefined?{"x-expected-season-version":String(version)}:{})}});const body=await response.json();if(!response.ok)throw new Error(body.message??"Operation failed");return body;};
  const loadOperations=async(next=filters)=>{const own=++loadSequence.current;if(!seasonId){setOperations(null);return;}setLoading(true);setError("");try{const query=new URLSearchParams(Object.entries(next).filter(([,value])=>value));const result=await request(`/api/operations/${encodeURIComponent(seasonId)}?${query}`);if(own===loadSequence.current)setOperations(result);}catch(value){if(own===loadSequence.current)setError(value.message??String(value));}finally{if(own===loadSequence.current)setLoading(false);}};
  useEffect(()=>{loadSequence.current++;setOperations(null);setReceipt(null);setRecovery(null);setFilters(emptyFilters);setTargetKey("");setPreview(null);void loadOperations(emptyFilters);return()=>{loadSequence.current++;};},[seasonId]);
  const target=operations?.correctionTargets?.find(item=>`${item.correctionType}:${item.targetId??""}`===targetKey);
  async function act(name,work){if(pending)return;setPending(name);setError("");try{return await work();}catch(value){setError(value.message??String(value));}finally{setPending("");}}
  async function backup(){await act("backup",async()=>{setReceipt(await request("/api/operations/backups",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({seasonId})}));await loadOperations();});}
  async function loadRecovery(){await act("recovery",async()=>setRecovery(await request("/api/operations/recovery")));}
  async function previewCorrection(){if(!target)return;await act("preview",async()=>setPreview(await request(`/api/operations/${encodeURIComponent(seasonId)}/corrections/preview`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({correctionType:target.correctionType,...(target.targetId?{targetId:target.targetId}:{})})})));}
  async function confirmCorrection(){await act("confirm",async()=>{await request(`/api/operations/corrections/${preview.id}/confirm`,{method:"POST",headers:{"content-type":"application/json","x-expected-season-version":String(preview.seasonVersion)},body:JSON.stringify({seasonId,expectedVersion:preview.seasonVersion,cutHash:preview.cutHash,backupHash:preview.backupHash,confirmation,reason})});setPreview(null);setConfirmation("");setReason("");await onChanged?.();});}
  return <section className="operations" aria-labelledby="operations-title" aria-busy={loading||Boolean(pending)}><header><p className="eyebrow">Exceptional workflows</p><h2 id="operations-title">Operations</h2><p>Browse canonical history, create backups, and preview audited corrections. Raw IDs appear only as secondary diagnostics.</p>{loading&&<p role="status">Loading Operations…</p>}{pending&&<p role="status">Operation in progress…</p>}</header>
    {!seasonId&&<p role="note">Load a season to browse its Operations records.</p>}
    <section aria-label="Backup and recovery"><h3>Backup & recovery</h3><button disabled={!seasonId||Boolean(pending)} onClick={backup}>Create verified backup</button><button disabled={Boolean(pending)} onClick={loadRecovery}>Show recovery summary</button>{receipt&&<p role="status">Verified backup: <code>{receipt.sha256}</code></p>}{recovery&&<div><p>Database integrity: {recovery.integrity}; schema {recovery.schemaVersion}.</p><p>Resume state: {recovery.activeSeason?.state??"No active season"}.</p>{recovery.interruptedOperations?.length>0&&<p>Interrupted temporary operations: {recovery.interruptedOperations.length}</p>}</div>}</section>
    <section aria-label="Audit timeline"><h3>Audit timeline</h3><div className="operations-filters"><label>Stage <select value={filters.stage} onChange={event=>setFilters({...filters,stage:event.target.value})}><option value="">All</option>{["SETUP","KEEPERS","AUCTION_1","AUCTION_2","DRAFT","OPERATIONS"].map(value=><option key={value}>{value}</option>)}</select></label><label>Command <input value={filters.commandType} onChange={event=>setFilters({...filters,commandType:event.target.value})}/></label><label>Entity <input value={filters.entityType} onChange={event=>setFilters({...filters,entityType:event.target.value})}/></label><label>Correlation <input value={filters.correlationId} onChange={event=>setFilters({...filters,correlationId:event.target.value})}/></label><label>Record state <select value={filters.recordState} onChange={event=>setFilters({...filters,recordState:event.target.value})}><option value="">All</option><option>ACTIVE</option><option>SUPERSEDED</option></select></label><label><input type="checkbox" checked={Boolean(filters.correctionLineage)} onChange={event=>setFilters({...filters,correctionLineage:event.target.checked?"true":""})}/> Correction lineage only</label><button onClick={()=>loadOperations(filters)} disabled={!seasonId||loading}>Apply filters</button></div>
      {operations&&<><p>Page {operations.timeline.page} of {operations.timeline.totalPages} · {operations.timeline.total} event(s)</p><ol className="audit-timeline">{operations.timeline.items.map(item=><li key={item.sequence}><strong>{item.commandType.replaceAll("_"," ")}</strong> · {item.stage} · {item.actorLabel}{item.reason?` · ${item.reason}`:""}<small>Sequence {item.sequence} · correlation <code>{item.correlationId}</code>{item.entityId?<> · diagnostic ID <code>{item.entityId}</code></>:null}</small></li>)}</ol><div><button disabled={loading||operations.timeline.page<=1} onClick={()=>loadOperations({...filters,page:operations.timeline.page-1})}>Previous page</button><button disabled={loading||operations.timeline.page>=operations.timeline.totalPages} onClick={()=>loadOperations({...filters,page:operations.timeline.page+1})}>Next page</button></div></>}</section>
    <section aria-label="Canonical and superseded records"><h3>Canonical & superseded records</h3><ul className="operations-records">{operations?.records?.map(item=><li key={`${item.kind}:${item.id}`}><strong>{item.label}</strong> · {item.kind} · {item.state}<span>{item.detail}</span><small>Diagnostic ID <code>{item.id}</code></small></li>)}</ul></section>
    <section aria-label="Audited correction"><h3>Audited correction</h3><label>Correction target <select aria-label="Correction target" value={targetKey} onChange={event=>{setTargetKey(event.target.value);setPreview(null);}}><option value="">Choose a labeled record</option>{operations?.correctionTargets?.map(item=><option key={`${item.correctionType}:${item.targetId??""}`} value={`${item.correctionType}:${item.targetId??""}`}>{item.label} · {item.detail}</option>)}</select></label><button disabled={!target||Boolean(pending)} onClick={previewCorrection}>Preview correction impact</button>{preview&&<div className="correction-preview"><p role="status">This correction affects {preview.manifest.length} record(s), resumes at {preview.resumeState}, and has verified backup {preview.backupId}.</p><ul>{preview.manifest.map(item=><li key={`${item.entityType}:${item.id}`}>{item.label??item.entityType}<small>{item.entityType} · diagnostic ID <code>{item.id}</code></small></li>)}</ul><label>Reason <input aria-label="Correction reason" value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Type CONFIRM ROLLBACK <input aria-label="Typed correction confirmation" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button disabled={Boolean(pending)||!reason.trim()||confirmation!=="CONFIRM ROLLBACK"} onClick={confirmCorrection}>Confirm audited rollback</button></div>}</section>
    <section aria-label="Stopped-server restore"><h3>Restore a backup</h3><p>Restore remains stopped-server-only. Stop the application, then run <code>npm run commissioner:restore -- &lt;database-path&gt; &lt;manifest-path&gt;</code>. The command verifies the checksum and retains a rollback copy.</p></section>{error&&<p role="alert">{error}</p>}
  </section>;
}
