import React, { useState } from "react";

export function OperationsPanel({ seasonId, seasonVersion, onChanged }) {
  const [receipt, setReceipt] = useState(null);
  const [recovery, setRecovery] = useState(null);
  const [error, setError] = useState("");
  const [correctionType, setCorrectionType] = useState("PICK");
  const [targetId, setTargetId] = useState("");
  const [reason, setReason] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [preview, setPreview] = useState(null);
  const request = async (path, options = {}) => { const version = typeof seasonVersion === "function" ? seasonVersion() : seasonVersion; const response = await fetch(path, { ...options, headers: { ...(options.headers ?? {}), "idempotency-key": crypto.randomUUID(), ...(version !== undefined ? { "x-expected-season-version": String(version) } : {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "Operation failed"); return body; };
  async function backup() { setError(""); try { setReceipt(await request("/api/operations/backups", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ seasonId }) })); } catch (value) { setError(String(value)); } }
  async function loadRecovery() { setError(""); try { setRecovery(await request("/api/operations/recovery")); } catch (value) { setError(String(value)); } }
  async function previewCorrection() { setError(""); try { setPreview(await request(`/api/operations/${seasonId}/corrections/preview`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ correctionType, ...(targetId ? { targetId } : {}) }) })); } catch (value) { setError(String(value)); } }
  async function confirmCorrection() { setError(""); try { await request(`/api/operations/corrections/${preview.id}/confirm`, { method: "POST", headers: { "content-type": "application/json", "x-expected-season-version": String(preview.seasonVersion) }, body: JSON.stringify({ seasonId, expectedVersion: preview.seasonVersion, cutHash: preview.cutHash, backupHash: preview.backupHash, confirmation, reason }) }); setPreview(null); setConfirmation(""); setReason(""); await onChanged?.(); } catch (value) { setError(String(value)); } }
  return <section aria-labelledby="operations-title"><h2 id="operations-title">Backup, recovery & corrections</h2><p>Create a verified local checkpoint before high-risk changes.</p><button type="button" onClick={backup}>Create verified backup</button><button type="button" onClick={loadRecovery}>Show recovery summary</button>{receipt && <p role="status">Verified backup: <code>{receipt.sha256}</code></p>}{recovery && <div><p>Database integrity: {recovery.integrity}; schema {recovery.schemaVersion}.</p><p>Resume state: {recovery.activeSeason?.state ?? "No active season"}.</p>{recovery.interruptedOperations?.length > 0 && <p>Interrupted temporary operations: {recovery.interruptedOperations.length}</p>}</div>}
    <h3>Audited correction</h3><label>Correction type <select aria-label="Correction type" value={correctionType} onChange={event => setCorrectionType(event.target.value)}>{["PICK", "AUCTION_REOPEN", "ROUND_1", "ROUND_2", "DRAFT_ORDER", "KEEPER"].map(type => <option key={type}>{type}</option>)}</select></label><label>Target ID <input aria-label="Correction target ID" value={targetId} onChange={event => setTargetId(event.target.value)} /></label><button disabled={!seasonId} onClick={previewCorrection}>Preview correction impact</button>{preview && <div><p role="status">Correction affects {preview.manifest.length} record(s) and resumes at {preview.resumeState}. Backup {preview.backupId} is verified.</p><label>Reason <input aria-label="Correction reason" value={reason} onChange={event => setReason(event.target.value)} /></label><label>Type CONFIRM ROLLBACK <input aria-label="Typed correction confirmation" value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label><button disabled={!reason.trim() || confirmation !== "CONFIRM ROLLBACK"} onClick={confirmCorrection}>Confirm audited rollback</button></div>}
    <h3>Restore a backup</h3><p>Restore is intentionally unavailable while the server owns the database. Stop the application, then run <code>npm run commissioner:restore -- &lt;database-path&gt; &lt;manifest-path&gt;</code>. The command verifies the checksum and retains a rollback copy.</p>{error && <p role="alert">{error}</p>}</section>;
}
