import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { CatalogPreparationService } from "../../src/application/catalog/catalog-preparation-service.js";
import { PricingService } from "../../src/application/pricing/pricing-service.js";
import { openSeasonStore } from "../../src/infrastructure/sqlite/season-store.js";
const actor={subjectId:"local:commissioner",type:"LOCAL_COMMISSIONER",label:"Commissioner",effectiveRole:"COMMISSIONER",context:{}} as const;
const meta=(key:string,type:string,version:number)=>({actor,seasonId:"s",idempotencyKey:key,commandType:type,expectedVersion:version});
async function fixture(){const store=await openSeasonStore(join(await mkdtemp(join(tmpdir(),"commissioner-pricing-")),"draft.db"));await store.execute({actor,seasonId:"s",idempotencyKey:"create",commandType:"CREATE_SEASON"},tx=>tx.createSeason({id:"s",leagueId:"l",year:2026,name:"Season",teamCount:1}));const catalog=await new CatalogPreparationService(store).stage(meta("catalog","STAGE_CATALOG",0),{bytes:Buffer.from(JSON.stringify([{externalId:"jj",name:"Justin Jefferson",position:"WR",nflTeam:"MIN"}])),format:"json",sourceNamespace:"sleeper"});await store.approveCatalog(meta("catalog-ok","APPROVE_CATALOG",1),catalog.id);await store.addCustomPlayer(meta("custom","ADD_CUSTOM_PLAYER",2),{id:"eddie",name:"Eddie Gallagher",position:"K",sourceType:"LEAGUE_CUSTOM"});return store;}

describe("durable price-list workflow",()=>{
  it("matches stable IDs, requires contextual approval, and applies manual > list > floor precedence",async()=>{const store=await fixture();await store.setPriceFloors(meta("floors","SET_PRICE_FLOORS",3),{WR:2,K:1});const service=new PricingService(store);const batch=await service.stage(meta("stage","STAGE_PRICE_LIST",4),{sourceLabel:"League sheet",format:"json",content:JSON.stringify([{sourceNamespace:"sleeper",sourceId:"jj",name:"Justin Jefferson",position:"WR",minimumBid:12},{name:"Eddie Gallagher",position:"K",minimumBid:3}])});expect(batch).toMatchObject({unresolvedCount:1,rows:[expect.objectContaining({matchKind:"STABLE_ID"}),expect.objectContaining({matchKind:"CONTEXT_PROPOSAL"})]});await expect(store.approvePriceList(meta("blocked","APPROVE_PRICE_LIST",5),batch.id)).rejects.toThrow(/unresolved/i);await store.setPriceDisposition(meta("resolve","REVIEW_PRICE_LIST",5),batch.id,2,"eddie");await store.approvePriceList(meta("approve","APPROVE_PRICE_LIST",6),batch.id);expect(await store.pricingSummary(actor,"s")).toMatchObject({players:expect.arrayContaining([expect.objectContaining({playerId:"eddie",minimumBid:3,source:"LIST"}),expect.objectContaining({minimumBid:12,source:"LIST"})]),preflight:{pricedCount:2,missingCount:0,unresolvedBatchCount:0}});await store.setManualPrice(meta("manual","SET_MANUAL_PRICE",7),"eddie",9);expect((await store.pricingSummary(actor,"s")).players.find(p=>p.playerId==="eddie")).toMatchObject({minimumBid:9,source:"MANUAL"});await store.setManualPrice(meta("clear","CLEAR_MANUAL_PRICE",8),"eddie");expect((await store.pricingSummary(actor,"s")).players.find(p=>p.playerId==="eddie")).toMatchObject({minimumBid:3,source:"LIST"});const replacement=await service.stage(meta("replace","STAGE_PRICE_LIST",9),{sourceLabel:"Replacement",format:"json",content:JSON.stringify([{sourceNamespace:"sleeper",sourceId:"jj",name:"Justin Jefferson",position:"WR",minimumBid:13}])});await store.approvePriceList(meta("replace-ok","APPROVE_PRICE_LIST",10),replacement.id);expect(await store.pricingSummary(actor,"s")).toMatchObject({players:expect.arrayContaining([expect.objectContaining({playerId:"eddie",minimumBid:1,source:"FLOOR"}),expect.objectContaining({minimumBid:13,source:"LIST"})])});await store.close();});

  it("blocks keeper lock while any staged price list remains unresolved",async()=>{const store=await fixture();await store.configureTeams(meta("teams","CONFIGURE_TEAMS",3),[{id:"a",displayName:"Alpha",seedOrder:1}]);await store.setPriceFloors(meta("floors","SET_PRICE_FLOORS",4),{QB:1,RB:1,WR:1,TE:1,K:1,DST:1});const batch=await new PricingService(store).stage(meta("stage","STAGE_PRICE_LIST",5),{sourceLabel:"Needs review",format:"json",content:JSON.stringify([{name:"Eddie Gallagher",position:"K",minimumBid:4}])});expect(batch.unresolvedCount).toBe(1);await expect(store.lockKeepers(meta("lock","LOCK_KEEPERS",6),14)).rejects.toThrow(/Price-list review/);expect((await store.getSeason(actor,"s"))?.state).toBe("SETUP");await store.close();});
});
