import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import Database from "better-sqlite3";
import { afterEach, describe, expect, it } from "vitest";
import { migrateDatabaseInPlace } from "../../src/infrastructure/sqlite/migrations.js";
import { ExportService } from "../../src/application/exports/export-service.js";
import type { BackupCoordinator } from "../../src/infrastructure/files/backup-coordinator.js";
import { BackupCoordinator as RealBackupCoordinator } from "../../src/infrastructure/files/backup-coordinator.js";

const directories:string[]=[];
afterEach(async()=>{for(const directory of directories.splice(0))await rm(directory,{recursive:true,force:true});});
async function fixture(){const directory=await mkdtemp(join(tmpdir(),"u7-export-"));directories.push(directory);const path=join(directory,"commissioner.db");migrateDatabaseInPlace(path);const db=new Database(path);db.exec(`INSERT INTO League(id,name) VALUES('l','League');INSERT INTO Season(id,leagueId,year,name,state,teamCount,rowVersion,active,createdAt,updatedAt) VALUES('s','l',2026,'Final','COMPLETED',1,9,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);INSERT INTO Team(id,leagueId,franchiseName) VALUES('t','l','Team, "One"');INSERT INTO SeasonTeam(id,seasonId,teamId,displayName,seedOrder,active) VALUES('st','s','t','Team, "One"',1,1);INSERT INTO ConventionalDraft(id,seasonId,status,contractVersion,createdAt,completedAt) VALUES('d','s','COMPLETED','fixed-order/1',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);`);const positions=["QB","QB","RB","RB","RB","WR","WR","WR","TE","TE","K","K","DST","DST"];for(const[index,position]of positions.entries()){const id=`p${index+1}`;const name=index===0?'Custom, "Quarterback"':`Player ${index+1}`;db.prepare("INSERT INTO Player(id,seasonId,name,position,sourceType,custom,available,keeperEligible,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run(id,"s",name,position,index===0?"LEAGUE_CUSTOM":"NFL",index===0?1:0,0,0);if(index===0)db.prepare("INSERT INTO RosterAssignment(id,seasonId,seasonTeamId,playerId,acquisitionSource,auctionRound,cost,sourceEntityId) VALUES(?,?,?,?,?,?,?,?)").run(`r${index}`,"s","st",id,"AUCTION",1,27,"award");else{db.prepare("INSERT INTO DraftPick(id,conventionalDraftId,overallPick,roundNumber,orderPosition,seasonTeamId,playerId,active,createdAt) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)").run(`pick${index}`,"d",index,index,1,"st",id,1);db.prepare("INSERT INTO RosterAssignment(id,seasonId,seasonTeamId,playerId,acquisitionSource,sourceEntityId) VALUES(?,?,?,?,?,?)").run(`r${index}`,"s","st",id,"CONVENTIONAL",`pick${index}`);}}db.close();return{directory,path};}
const rules={limits:{QB:2,RB:2,WR:3,TE:2,K:2,DST:2},flexEligible:["RB","WR","TE"],flexCapacity:1};

describe("deterministic completed-season exports",()=>{
  it("writes stable JSON/CSV with custom-player, auction, and pick metadata",async()=>{const{directory,path}=await fixture();const service=new ExportService(path,join(directory,"backups"));const first=await service.export("s",join(directory,"one"),rules);const second=await service.export("s",join(directory,"two"),rules);expect(await readFile(first.jsonPath)).toEqual(await readFile(second.jsonPath));expect(await readFile(first.csvPath)).toEqual(await readFile(second.csvPath));const json=JSON.parse(await readFile(first.jsonPath,"utf8"));expect(json.rosters[0].players[0]).toMatchObject({name:'Custom, "Quarterback"',custom:true,acquisition:{source:"AUCTION",auctionRound:1,cost:27}});expect(await readFile(first.csvPath,"utf8")).toContain('"Custom, ""Quarterback"""');});
  it("restores the pre-export checkpoint into a clean database and reproduces identical bytes",async()=>{const{directory,path}=await fixture();const first=await new ExportService(path,join(directory,"backups")).export("s",join(directory,"one"),rules);const db=new Database(path,{readonly:true});const manifestPath=String((db.prepare("SELECT manifestPath FROM BackupRecord WHERE trigger='PRE_EXPORT' ORDER BY createdAt LIMIT 1").get()as{manifestPath:string}).manifestPath);db.close();const clean=join(directory,"clean.db");migrateDatabaseInPlace(clean);await new RealBackupCoordinator(clean).restore(manifestPath);const replay=await new ExportService(clean,join(directory,"clean-backups")).export("s",join(directory,"replay"),rules);expect(await readFile(replay.jsonPath)).toEqual(await readFile(first.jsonPath));expect(await readFile(replay.csvPath)).toEqual(await readFile(first.csvPath));});
  it("blocks incomplete seasons and backup failures without recording an export",async()=>{const{directory,path}=await fixture();const db=new Database(path);db.prepare("UPDATE Season SET state='CONVENTIONAL_DRAFT'").run();db.close();await expect(new ExportService(path,join(directory,"backups")).export("s",join(directory,"out"),rules)).rejects.toThrow(/complete/i);const reset=new Database(path);reset.prepare("UPDATE Season SET state='COMPLETED'").run();reset.close();const failing={create:async()=>{throw new Error("backup failed");}} as unknown as BackupCoordinator;await expect(new ExportService(path,join(directory,"backups"),failing).export("s",join(directory,"out"),rules)).rejects.toThrow("backup failed");const check=new Database(path);expect((check.prepare("SELECT count(*) count FROM ExportRecord").get()as{count:number}).count).toBe(0);check.close();});
});
