import type Database from "better-sqlite3";
import type { CorrectionType, DependencyItem } from "./correction-types.js";
const rows = (db: Database.Database, sql: string, values: unknown[] = []) => db.prepare(sql).all(...values) as Array<{id:string; orderValue?:number}>;
export function dependencyCut(db: Database.Database, seasonId: string, type: CorrectionType, targetId?: string): DependencyItem[] {
  const result: DependencyItem[] = []; const add = (entityType: string, found: Array<{id:string;orderValue?:number}>) => found.forEach((item,index)=>result.push({entityType,id:item.id,order:item.orderValue??index}));
  add("ExportRecord",rows(db,"SELECT id FROM ExportRecord WHERE seasonId=? AND supersededAt IS NULL",[seasonId]));
  if (type === "PICK") { const target=db.prepare("SELECT overallPick FROM DraftPick WHERE id=? AND active=1").get(targetId) as {overallPick:number}|undefined; if(!target) throw new Error("Active draft pick not found"); add("DraftPick",rows(db,"SELECT p.id,p.overallPick orderValue FROM DraftPick p JOIN ConventionalDraft d ON d.id=p.conventionalDraftId WHERE d.seasonId=? AND p.active=1 AND p.overallPick>=? ORDER BY p.overallPick",[seasonId,target.overallPick])); }
  else {
    if (["KEEPER","ROUND_1","ROUND_2","DRAFT_ORDER"].includes(type)) { add("DraftPick",rows(db,"SELECT p.id,p.overallPick orderValue FROM DraftPick p JOIN ConventionalDraft d ON d.id=p.conventionalDraftId WHERE d.seasonId=? AND p.active=1 ORDER BY p.overallPick",[seasonId])); add("DraftOrderEntry",rows(db,"SELECT e.id FROM DraftOrderEntry e JOIN ConventionalDraft d ON d.id=e.conventionalDraftId WHERE d.seasonId=? AND e.supersededAt IS NULL",[seasonId])); add("DraftOrderTieDecision",rows(db,"SELECT t.id FROM DraftOrderTieDecision t JOIN ConventionalDraft d ON d.id=t.conventionalDraftId WHERE d.seasonId=? AND t.supersededAt IS NULL",[seasonId])); }
    const rounds=type==="KEEPER"||type==="ROUND_1"?[1,2]:type==="ROUND_2"?[2]:[]; for(const round of rounds){ add("AuctionRound",rows(db,"SELECT id FROM AuctionRound WHERE seasonId=? AND roundNumber=? AND supersededAt IS NULL",[seasonId,round])); add("AuctionAttempt",rows(db,"SELECT a.id FROM AuctionAttempt a JOIN AuctionRound r ON r.id=a.roundId WHERE r.seasonId=? AND r.roundNumber=? AND a.supersededAt IS NULL",[seasonId,round])); add("AuctionTieDecision",rows(db,"SELECT t.id FROM AuctionTieDecision t JOIN AuctionRound r ON r.id=t.roundId WHERE r.seasonId=? AND r.roundNumber=? AND t.supersededAt IS NULL",[seasonId,round])); add("AuctionAward",rows(db,"SELECT a.id FROM AuctionAward a JOIN AuctionRound r ON r.id=a.roundId WHERE r.seasonId=? AND r.roundNumber=? AND a.supersededAt IS NULL",[seasonId,round])); add("TeamAuctionBalance",rows(db,"SELECT id FROM TeamAuctionBalance WHERE seasonId=? AND roundNumber=? AND supersededAt IS NULL",[seasonId,round])); }
    if(type==="AUCTION_REOPEN"){if(!targetId)throw new Error("Auction round target is required");add("AuctionAttempt",rows(db,"SELECT id FROM AuctionAttempt WHERE roundId=? AND supersededAt IS NULL",[targetId]));add("AuctionTieDecision",rows(db,"SELECT id FROM AuctionTieDecision WHERE roundId=? AND supersededAt IS NULL",[targetId]));}
    if(type==="KEEPER")add("KeeperSelection",rows(db,"SELECT id FROM KeeperSelection WHERE seasonId=? AND supersededAt IS NULL",[seasonId]));
  }
  return result.sort((a,b)=>a.entityType.localeCompare(b.entityType)||a.order-b.order||a.id.localeCompare(b.id));
}
export const resumeState=(type:CorrectionType)=>type==="KEEPER"?"SETUP":type==="ROUND_1"?"R1_BIDDING":type==="ROUND_2"?"R2_BIDDING":type==="DRAFT_ORDER"?"R2_PUBLISHED":type==="AUCTION_REOPEN"?"R1_BIDDING":"CONVENTIONAL_DRAFT";
